import type {
  Carrier,
  ClientContract,
  ExecutiveKpiSnapshot,
  InventoryItem,
  ReturnRequest,
  Shipment,
  Warehouse,
} from "../types/entities.js";

export const warehouses: Warehouse[] = [
  {
    warehouseId: "wh-la",
    city: "Los Angeles",
    country: "US",
    managedBy: "Ana Whitfield",
    operatorsCount: 38,
    managementSystem: "commercial_software",
  },
  {
    warehouseId: "wh-zgz",
    city: "Zaragoza",
    country: "ES",
    managedBy: "Ana Whitfield",
    operatorsCount: 32,
    managementSystem: "advanced_spreadsheet",
  },
];

export const inventoryItems: InventoryItem[] = [
  {
    sku: "SKU-1001",
    warehouseId: "wh-la",
    stockUnits: 420,
    lowStockThreshold: 100,
    updatedAtISO: "2026-07-08T10:00:00.000Z",
  },
  {
    sku: "SKU-1001",
    warehouseId: "wh-zgz",
    stockUnits: 180,
    lowStockThreshold: 90,
    updatedAtISO: "2026-07-08T10:05:00.000Z",
  },
];

export const carriers: Carrier[] = [
  {
    carrierId: "car-1",
    name: "UPS",
    countries: ["US"],
    supportsTrackingApi: true,
    onTimeRate: 0.95,
    incidentsPer100Shipments: 1.6,
    costPerKgEUR: 2.9,
  },
  {
    carrierId: "car-2",
    name: "FedEx",
    countries: ["US"],
    supportsTrackingApi: true,
    onTimeRate: 0.93,
    incidentsPer100Shipments: 2.1,
    costPerKgEUR: 3.1,
  },
  {
    carrierId: "car-3",
    name: "DHL",
    countries: ["US", "ES"],
    supportsTrackingApi: true,
    onTimeRate: 0.94,
    incidentsPer100Shipments: 1.8,
    costPerKgEUR: 3.2,
  },
  {
    carrierId: "car-4",
    name: "MRW",
    countries: ["ES"],
    supportsTrackingApi: true,
    onTimeRate: 0.91,
    incidentsPer100Shipments: 2.3,
    costPerKgEUR: 2.4,
  },
  {
    carrierId: "car-5",
    name: "SEUR",
    countries: ["ES"],
    supportsTrackingApi: true,
    onTimeRate: 0.92,
    incidentsPer100Shipments: 2,
    costPerKgEUR: 2.5,
  },
  {
    carrierId: "car-6",
    name: "LocalCarrierUS",
    countries: ["US"],
    supportsTrackingApi: false,
    onTimeRate: 0.88,
    incidentsPer100Shipments: 3.8,
    costPerKgEUR: 2,
  },
  {
    carrierId: "car-7",
    name: "LocalCarrierES",
    countries: ["ES"],
    supportsTrackingApi: false,
    onTimeRate: 0.89,
    incidentsPer100Shipments: 3.1,
    costPerKgEUR: 2.1,
  },
  {
    carrierId: "car-8",
    name: "CrossBorderExpress",
    countries: ["US", "ES"],
    supportsTrackingApi: true,
    onTimeRate: 0.9,
    incidentsPer100Shipments: 2.6,
    costPerKgEUR: 3.4,
  },
];

export const shipments: Shipment[] = [
  {
    shipmentId: "sh-1001",
    orderId: "ord-1001",
    destinationCountry: "US",
    destinationPostalCode: "90001",
    carrierName: "UPS",
    urgency: "standard",
    weightKg: 2.4,
    status: "delivered",
    operationalCostEUR: 7.2,
    shippedAtISO: "2026-07-05T12:00:00.000Z",
  },
  {
    shipmentId: "sh-1002",
    orderId: "ord-1002",
    destinationCountry: "ES",
    destinationPostalCode: "50001",
    carrierName: "SEUR",
    urgency: "express",
    weightKg: 1.2,
    status: "in_transit",
    operationalCostEUR: 4.3,
    shippedAtISO: "2026-07-06T14:00:00.000Z",
  },
  {
    shipmentId: "sh-1003",
    orderId: "ord-1003",
    destinationCountry: "ES",
    destinationPostalCode: "28001",
    carrierName: "DHL",
    urgency: "same_day",
    weightKg: 3.8,
    status: "failed",
    operationalCostEUR: 11.7,
    shippedAtISO: "2026-07-06T17:00:00.000Z",
  },
  {
    shipmentId: "sh-1004",
    orderId: "ord-1004",
    destinationCountry: "US",
    destinationPostalCode: "10001",
    carrierName: "FedEx",
    urgency: "express",
    weightKg: 0.8,
    status: "pending",
    operationalCostEUR: 3.6,
    shippedAtISO: "2026-07-07T09:30:00.000Z",
  },
  {
    shipmentId: "sh-1005",
    orderId: "ord-1005",
    destinationCountry: "US",
    destinationPostalCode: "73301",
    carrierName: "LocalCarrierUS",
    urgency: "standard",
    weightKg: 5.1,
    status: "lost",
    operationalCostEUR: 10.1,
    shippedAtISO: "2026-07-07T16:45:00.000Z",
  },
];

export const returnRequests: ReturnRequest[] = [
  {
    returnId: "ret-2001",
    shipmentId: "sh-1001",
    clientId: "client-1",
    country: "US",
    reason: "Damaged package",
    decision: "approved",
    disposition: "refurbish",
    requestedAtISO: "2026-07-07T11:00:00.000Z",
    inspectedAtISO: "2026-07-08T09:00:00.000Z",
  },
  {
    returnId: "ret-2002",
    shipmentId: "sh-1003",
    clientId: "client-2",
    country: "ES",
    reason: "Wrong size",
    decision: "manual_review",
    disposition: "pending",
    requestedAtISO: "2026-07-08T13:20:00.000Z",
    inspectedAtISO: null,
  },
];

export const clientContracts: ClientContract[] = [
  {
    clientId: "client-1",
    clientName: "NorthPacific Store",
    country: "US",
    annualContractValueEUR: 180000,
    startsAtISO: "2026-01-01T00:00:00.000Z",
    endsAtISO: "2027-01-01T00:00:00.000Z",
    renewalRiskScore: 32,
  },
  {
    clientId: "client-2",
    clientName: "Iberia Moda",
    country: "ES",
    annualContractValueEUR: 145000,
    startsAtISO: "2026-02-01T00:00:00.000Z",
    endsAtISO: "2027-02-01T00:00:00.000Z",
    renewalRiskScore: 47,
  },
];

export const executiveKpis: ExecutiveKpiSnapshot[] = [
  {
    country: "US",
    shipmentsVolume: 12600,
    onTimeDeliveryRate: 0.93,
    operationalCostEUR: 214000,
    returnsRate: 0.19,
    customerSatisfactionScore: 84,
    generatedAtISO: "2026-07-07T07:00:00.000Z",
  },
  {
    country: "ES",
    shipmentsVolume: 9800,
    onTimeDeliveryRate: 0.91,
    operationalCostEUR: 176000,
    returnsRate: 0.22,
    customerSatisfactionScore: 81,
    generatedAtISO: "2026-07-07T07:00:00.000Z",
  },
];